services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CHROME_BIN=/usr/bin/google-chrome
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
      - COMPOSE_BAKE=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 