services:
  - type: web
    name: attendance-calculator
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      # Install Chrome and its dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg2 \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        xdg-utils \
        libu2f-udev \
        libvulkan1

      # Add Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      
      # Install Chrome
      apt-get update && apt-get install -y google-chrome-stable --no-install-recommends
      apt-get clean && rm -rf /var/lib/apt/lists/*

      # Set Puppeteer environment variables
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
      
      # Clean install dependencies
      rm -rf node_modules
      rm -f package-lock.json
      npm cache clean --force
      npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: CORS_ORIGIN
        value: https://attendance-calculator.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "50"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE_PATH
        value: ./logs
      - key: NAVIGATION_TIMEOUT
        value: "60000"
      - key: REQUEST_TIMEOUT
        value: "60000"
      - key: BROWSER_TIMEOUT
        value: "60000"
      - key: MAX_MEMORY_RESTART
        value: "1G"
      - key: SAMVIDHA_URL
        value: https://samvidha.iare.ac.in/
      - key: SAMVIDHA_LOGIN_TIMEOUT
        value: "60000"
      - key: SAMVIDHA_NAVIGATION_TIMEOUT
        value: "60000"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: logs
      mountPath: /app/logs
      sizeGB: 1
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - backend/**
        - frontend/**
