services:
  - type: web
    name: attendance-calculator
    runtime: node
    buildCommand: |
      # Install Chrome and its dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg2 \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        xdg-utils \
        libu2f-udev \
        libvulkan1

      # Add Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

      # Install Chrome
      apt-get update && apt-get install -y google-chrome-stable --no-install-recommends
      apt-get clean && rm -rf /var/lib/apt/lists/*

      # Set environment variables
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
      export CHROME_BIN=/usr/bin/google-chrome

      # Install production dependencies
      npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
