services:
  - type: web
    name: attendance-calculator
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.render/chrome/opt/google/chrome/google-chrome
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: BROWSER_POOL_MAX
        value: 2
      - key: BROWSER_POOL_MIN
        value: 1
      - key: CACHE_TTL
        value: 3600
      - key: CACHE_MAX_KEYS
        value: 1000
    plan: free