services:
  - type: web
    name: attendance-calculator
    env: node
    buildCommand: |
      # Install Chrome dependencies
      apt-get update && apt-get install -y wget gnupg2 ca-certificates
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update && apt-get install -y google-chrome-stable --no-install-recommends
      apt-get clean && rm -rf /var/lib/apt/lists/*
      # Install Node.js dependencies
      npm ci --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - backend/**
        - frontend/**
