services:
  - type: web
    name: attendance-calculator
    runtime: docker
    dockerfilePath: Dockerfile
    buildCommand: "true"
    startCommand: "npm start"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
