services:
  - type: web
    name: attendance-calculator
    env: node
    region: oregon  # Specify a region for better performance
    plan: free   # Specify the plan type
    buildCommand: |
<<<<<<< HEAD
      apt-get update && apt-get install -y \
      chromium \
      chromium-driver \
      fonts-ipafont-gothic \
      fonts-wqy-zenhei \
      fonts-thai-tlwg \
      fonts-kacst \
      fonts-freefont-ttf \
      --no-install-recommends \
      && rm -rf /var/lib/apt/lists/* \
      && npm ci --production
    startCommand: node backend/server.js
=======
      # Install Chrome dependencies
      apt-get update && apt-get install -y wget gnupg2 ca-certificates
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update && apt-get install -y google-chrome-stable --no-install-recommends
      apt-get clean && rm -rf /var/lib/apt/lists/*
      # Install Node.js dependencies with Puppeteer skip
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --production
    startCommand: npm start
>>>>>>> 6b55f4202ffd5ca4a6ebd5f59c8863b3cb91518c
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: CORS_ORIGIN
        value: https://attendance-calculator.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "50"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE_PATH
        value: ./logs
      - key: NAVIGATION_TIMEOUT
        value: "30000"
      - key: REQUEST_TIMEOUT
        value: "30000"
      - key: BROWSER_TIMEOUT
        value: "30000"
      - key: MAX_MEMORY_RESTART
        value: "1G"
      - key: SAMVIDHA_URL
        value: https://samvidha.iare.ac.in/
      - key: SAMVIDHA_LOGIN_TIMEOUT
        value: "30000"
      - key: SAMVIDHA_NAVIGATION_TIMEOUT
        value: "30000"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: logs
      mountPath: /app/logs
      sizeGB: 1
    env: node
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - backend/**
        - frontend/**
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains 
